trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    npm install
    npm test
  displayName: 'npm install and test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: './test-results/jest/results.xml'
    testRunTitle: 'Jest Unit Tests'
